### ISSUE TITLE
service-application

### ISSUE THREAD

**Issue by getvega** [cubyn/node-carotte-amqp#46]

**Comment by nbeydoon** [comment]
# controllers

## apps

- [ ] get app
- [ ] update app
- [ ] create app
- [ ] list app
- [ ] delete app
- [ ] invoke (to specified)

## app classes

- [ ] list application classes

**Comment by nbeydoon** [comment]
Issue moved to [cubyn/service-application #1](https://github.com/cubyn/service-application/issues/1) via [**ZenHub**](https://www.zenhub.com/)
